### ISSUE TITLE
Update Manual for "New Config File" Commit

### ISSUE THREAD

**Issue by theCapypara** [Parakoopa/GMnet-manual#10]
Update might not be necessary, in this case simply close this issue.
https://github.com/Parakoopa/GMnet-ENGINE/commit/343ab7492971501c7c1334f8ef0782959d04efc1

**Comment by The-any-Key** [comment]
Fixed in 718825136cd3186c9a9288f7cc8fa27de434920a

**Comment by The-any-Key** [comment]
More fix in dbc1db09a43c4a39c8f23c35fff763784c52c5d8
