### ISSUE TITLE
Update Manual for Pull Request #4 (Punch improvements)

### ISSUE THREAD

**Issue by theCapypara** [Parakoopa/GMnet-manual#12]
Update might not be necessary, in this case simply close this issue.
https://github.com/Parakoopa/GMnet-ENGINE/pull/4

**Comment by The-any-Key** [comment]
Fixed in 3075f3b15f3dbcbeab04985a37cac673a1763240

**Comment by theCapypara** [comment]
Did you also update the PUNCH manual, especially the tutorial? It wasn't linked in the document tree before, I added it with a373ac7 ; could you also check your other issues again? Sorry it wasn't visible before :(
