### ISSUE TITLE
Update Manual for Commit "Debugoverlay: Map List and Count"

### ISSUE THREAD

**Issue by theCapypara** [Parakoopa/GMnet-manual#16]
Update might not be necessary, in this case simply close this issue.
https://github.com/Parakoopa/GMnet-ENGINE/commit/179e55761dcfaec9fb802481a20269b6301fa488

**Comment by The-any-Key** [comment]
Fixed in 9a24f4b4bdbb8b1fa45fed68ab23bac6785331d0
