### ISSUE TITLE
Add depth 1 to the time object

### ISSUE THREAD

**Issue by The-any-Key** [Parakoopa/GMnet-manual#2]
Need to add depth=1 to the time object else the connecting player is drawn behind the time object rectangle.

https://gmnet-engine.org/manual/engine/tutorial/10_time

**Comment by The-any-Key** [comment]
Fixed in 50fe09d565c5d366248e151bf2d61b17666a31a0

**Comment by The-any-Key** [comment]
Ok. Somehow some text did not commit in 50fe09d. But now fixed in 0df69cb82658a68b9367d2b36dc9aa66ba66c992

**Comment by cbergqvist** [comment]
Any chances of updating https://gmnet-engine.org/manual/engine/tutorial/10_time to reflect the above commits? Ran into the depth issue following the tutorial but managed to work around it.
