### ISSUE TITLE
Update Manual for Pull Request #19 (Upnp feature add)

### ISSUE THREAD

**Issue by theCapypara** [Parakoopa/GMnet-manual#23]
Update might not be necessary, in this case simply close this issue.
https://github.com/Parakoopa/GMnet-ENGINE/pull/19

**Comment by The-any-Key** [comment]
Must wait with this one. Upnp don't work right now because the server must send his internal port number to the client so the engine can use it.

**Comment by theCapypara** [comment]
Right, forgot about that. Could you open a thread on the forums to discuss how we would do this?

**Comment by The-any-Key** [comment]
I simply use data4 and added some code to the punch script that handles it.
But I also created a script so you can add multiple strings in a single data variable. You will never run out of data variables. This script also show number of connected player in the lobbys.

I created a thread here:
https://gmnet-engine.org/forum/viewtopic.php?f=12&t=240

**Comment by theCapypara** [comment]
I'd say we should document what we have right now anyway. Even though upnp is basically useless right now when combined with the current master server, we should still document, that it exists and how it can be enabled. Along with a notice on why it's useless right now. Proper support will be added in 1.4.0.

If you write the article it, use the "note" blocks for this notice, as seen in 3_udphp2.rst, and add it to the top.

Please create a new topic under "conepts" in the engine manual.

If you need any help with syntax or anything like that, let me know :)

PS: I just noticed we implemented upnp in GMnet ENGINE, wouldn't it be more useful in PUNCH? Right now it's started in htme_serverStart, maybe we should move everything to the udphp_ scripts, so it also works with GMnet PUNCH alone. If you want to you can do this and open a pull request on the main repo if you are done. In this case also create a article on how to use UPNP with only PUNCH in the punch manual. Again, if you have any questions, feel free to ask.

**Comment by theCapypara** [comment]
Here is everything I said above a little more structured as a TODO list:

For 1.3.2:
- Move upnp support away from the htme_ scripts, into the udphp_scripts that way UPNP will also work with just GMnet PUNCH. This also means the configuration variable has to be added to GMnet PUNCH as well and synced between ENGINE and PUNCH.
- Update the manual for both GMnet products, create a new article for both, include a short explanation, a notice why it doesn't work as expected right now and a explanation on how to enable and disable it.

For 1.4.0:
- We add support for multiple ports to GMnet PUNCH and let the new master server send the original server port as well.

if there is an error in my logic, let me know :laughing:

**Comment by The-any-Key** [comment]
Ok. I will move:
htme_config:

`self.upnp_enabled = false;`

htme_serverStart:

```
// Start upnp
if upnp_enabled
{
    // Create a upnp handler
    if instance_number(obj_upnp)=0 instance_create(0,0,obj_upnp);
    if instance_number(obj_upnp)>0
    {
        // Set port to setup
        obj_upnp.port_to_set=port;
        // Start the setup
        with obj_upnp event_user(0);
    }
}
```

To

udphp_config and udphp_createServer

What do we do with the obj_upnp?
We need to use this htme to get the router ip for andoid devices.

```
with global.htme_object
{
    if self.socketOrServer>-1
    {
        buffer_seek(self.buffer, buffer_seek_start, 0);
        buffer_write(self.buffer, buffer_s8, htme_packet.GETLOCALIPBROADCAST);
        buffer_write(self.buffer, buffer_string, other.upnp_id);
        network_send_broadcast(self.socketOrServer, self.port, self.buffer, buffer_tell(self.buffer));
    }
}
```

**Comment by theCapypara** [comment]
Can't we use this on both punch and engine? We'd just need to change the htme_packet enum to an udphp_packet enum. And we'll I guess we have to find a way of not using this with obj_htme. I know that udphp also as a reference to the buffer. So we could check if udphp is enabled using the corresponding global udphp_ Variable and then get the buffer from another udphp_ Variable. Same for the server socket.

**Comment by The-any-Key** [comment]
I can test this.

**Comment by The-any-Key** [comment]
htme change is now in https://github.com/Parakoopa/GMnet-ENGINE/pull/35

Tested and work on Windows, android

**Comment by The-any-Key** [comment]
Manual add in d3bed51dbcb4514771d4081c4aca831f01115c25

**Comment by theCapypara** [comment]
Did small adjustments in t 80fb8c4, I think this issue is done now, if not leave a comment :smile:
